version: "3"
services:
  camunda:
    image: 'camunda/camunda-bpm-platform:latest'
    ports:
      - '8080:8080'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - C:\docker_data:/camunda/webapps/camunda/app/tasklist/default/forms
