apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: camunda
      service: camunda
  template:
    metadata:
      labels:
        app: camunda
        service: camunda
    spec:
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:latest
          ports:
            - containerPort: 8080
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            # - name: JAVA_OPTS
            #   value: "-XX:-UseContainerSupport"
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "600Mi"
              cpu: "500m"
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 180
            httpGet:
              path: /engine-rest/version
              port: 8080
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 180
            periodSeconds: 180
            httpGet:
              path: /engine-rest/version
              port: 8080
            timeoutSeconds: 5
      restartPolicy: Always

