apiVersion: v1
kind: Service
metadata:
  name: camundaservice
  namespace: {{ .Values.namespace }}
  labels:
    app: camunda
    service: camundaservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: camunda
    service: camunda

---

apiVersion: v1
kind: Service
metadata:
  name: camundaservicenp
  namespace: {{ .Values.namespace }}
  labels:
    app: camunda
    service: camundaservicenp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100
  selector:
    app: camunda
    service: camunda
