@server = http://camunda.danny-thibaudeau.ca
@camundaRestEngine = {{server}}/engine-rest

###

POST http://192.168.1.225/engine-rest/process-definition/Process_16n18ma:11:2a4d45d4-e6f3-11ea-bb89-0242ac130002/start HTTP/1.1
content-type: application/json
Accept: application/json

{

}

###

POST http://camunda.danny-thibaudeau.ca/engine-rest/message HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "messageName" : "startUserProcessMsg"
}


###

GET {{camundaRestEngine}}/task?candidateGroup=testGroup HTTP/1.1
Content-Type:  application/json
Accept: application/json

###

GET {{camundaRestEngine}}/task/7bc78fec-e882-11ea-932a-0242ac120002/form-variables HTTP/1.1
Content-Type:  application/json
